# name: Linting

# on: [push, pull_request]

# jobs:

#   Linting:

#     runs-on: ubuntu-latest

#     steps:

#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           ref: ${{ github.head_ref }}

#       - name: Skip if Pull Request
#         if: github.event_name == 'pull_request'
#         run: exit 0


#       - name: Lint code with prettier
#         uses: creyD/prettier_action@v4.3
#         with:
#           prettier_options: --write **/*.{js,md}
